version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx_server # Usamos variable de entorno para prefijo
    ports:
      - "8080:80" # Nginx sigue escuchando en el puerto 8080 del host
    volumes:
      - ./html:/var/www/html # Archivos estáticos y quizás la base del frontend JS
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Configuración Nginx
      # El sitio estático generado por Eleventy podría servirse por Nginx en producción,
      # montando ./docs/_site en una ubicación que Nginx sirva. Ejemplo:
      # - ./docs/_site:/var/www/docs_static 
    depends_on:
      - php
      - api
    restart: always

  php:
    image: php:8.2-fpm-alpine
    container_name: php_server
    volumes:
      - ./html:/var/www/html # Código PHP (si lo usas)
      - ./data:/data
      - ./logs:/var/log/myapp
    environment:
      - GEMMA_API_KEY=${GEMMA_API_KEY} # Lee la variable del entorno del host
    restart: always

  api:
    image: node:18-alpine
    container_name: node_api_server
    working_dir: /app
    volumes:
      - ./api:/app
    expose: # No se mapea al host directamente, Nginx lo proxyaría si fuera necesario
      - "3000"
    command: node server.js # O 'npm run dev' si usas nodemon
    restart: always
    environment:
      - NODE_ENV=development
    # user: "node"

  # ---- NUEVO SERVICIO ELEVENTY ----

  eleventy_docs:
    image: node:lts
    container_name: eleventy_docs
    working_dir: /app
    environment:
      # Mantenemos el polling para detección de cambios fiable
      - CHOKIDAR_USEPOLLING=1
    # Comando SIN --output (definido en .eleventy.js)
    # Mantenemos --serve (que ahora se configura con setBrowserSyncConfig)
    command: sh -c "npm install && npx @11ty/eleventy --serve"
    ports:
      # Acceso desde http://localhost:8081 en tu host
      - "8081:8080"
    volumes:
      # Tu código fuente (incluyendo .eleventy.js, _includes, tus .md, etc.)
      - ./docs_src:/app
      # La carpeta padre donde Eleventy creará la subcarpeta 'docs'
      - ./html:/build_output
      # Opcional: volumen para node_modules
      # - /app/node_modules
    restart: unless-stopped

networks:
  default:

# Definición opcional del volumen nombrado (solo si usas el volumen de node_modules)
# volumes:
#   eleventy_node_modules: