version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx_server # Usamos variable de entorno para prefijo
    ports:
      - "8080:80" # Nginx sigue escuchando en el puerto 8080 del host
    volumes:
      - ./html:/var/www/html # Archivos estáticos y quizás la base del frontend JS
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Configuración Nginx
      # El sitio estático generado por Eleventy podría servirse por Nginx en producción,
      # montando ./docs/_site en una ubicación que Nginx sirva. Ejemplo:
      # - ./docs/_site:/var/www/docs_static 
    depends_on:
      - php
      - api
    restart: always

  php:
    image: php:8.2-fpm-alpine
    container_name: php_server
    volumes:
      - ./html:/var/www/html # Código PHP (si lo usas)
      - ./data:/data
      - ./logs:/var/log/myapp
    environment:
      - GEMMA_API_KEY=${GEMMA_API_KEY} # Lee la variable del entorno del host
    restart: always

  api:
    image: node:18-alpine
    container_name: node_api_server
    working_dir: /app
    volumes:
      - ./api:/app
    expose: # No se mapea al host directamente, Nginx lo proxyaría si fuera necesario
      - "3000"
    command: node server.js # O 'npm run dev' si usas nodemon
    restart: always
    environment:
      - NODE_ENV=development
    # user: "node"

networks:
  default:

